
// Generated by the WOLips Templateengine Plug-in at 22-Nov-2023 3:23:11 PMpackage ;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.eocontrol.EOFetchSpecification;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

import er.rest.routes.jsr311.DELETE;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	DeptForm dept = null;
	NSArray<DeptForm> presentDeptList = new NSMutableArray<DeptForm>();
	boolean c1 = true,c2=false;
	
	
	public Main(WOContext context) {
		super(context);
		presentDeptList = getAlldeptList();
		dept = new DeptForm();
	}

	private NSArray<DeptForm> getAlldeptList() {
		EOFetchSpecification eof = new EOFetchSpecification("DeptForm", null, null);
		return session().defaultEditingContext().objectsWithFetchSpecification(eof);
	}

	public WOComponent saveButton() {
		dept.setRemoveCheck("false");
		for (int i = 0; i < presentDeptList.size(); i++) {
			if(presentDeptList.get(i).deptID().equals(dept.deptID())) {
				c2=true;
				Main m=(Main) pageWithName("Main");
				m.c2=true;
				return m;
			}
			
		}
		if(!c2) {
		session().defaultEditingContext().insertObject(dept);
		session().defaultEditingContext().saveChanges();
		dept = new DeptForm();
		}
		
		return pageWithName("DeptDetails");
	}

	public void backButton() {
		c1 = false;
	}

}
