// Generated by the WOLips Templateengine Plug-in at 22-Nov-2023 3:23:11 PM

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
